// src/renderer/components/SaverSummary.vue
<template>
  <div class="saver-description">
    <h1>
      {{ name }} <small><a
        v-if="hasUrl"
        :href="aboutUrl"
        @click="open"
      >learn more</a></small>
    </h1>
    <template v-if="saver.editable">
      <div class="actions">
        <button
          class="btn btn-outline-secondary btn-sm edit" 
          href="#"
          role="button" 
          :data-name="saver.name" 
          @click.stop="onEditClick(saver)"
        >
          edit
        </button>
        <button
          class="btn btn-outline-secondary btn-sm" 
          href="#"
          role="button" 
          @click.stop="onDeleteClick(saver)"
        >
          delete
        </button>
      </div>
    </template>

    <p>{{ description }}</p>
    <span v-if="hasAuthor">
      by: {{ author }}
    </span>
  </div>
</template>

<script>
const ipcRenderer = window.ipcRenderer;

export default {
  name: "SaverSummary",
  components: { },
  props: ["saver"],
  computed: {
    name() {
      return this.saver.name;
    },
    aboutUrl() {
      return this.saver.aboutUrl;
    },
    hasUrl() {
      return this.saver.aboutUrl !== undefined &&
        this.saver.aboutUrl !== "";
    },
    description() {
      return this.saver.description;
    },
    author() {
      return this.saver.author;
    },
    hasAuthor() {
      return this.saver.author !== undefined &&
        this.saver.author !== "";
    }
  },
  methods: {
    open(evt) {
      evt.preventDefault();
      ipcRenderer.send("launch-url", event.target.href);
    },
    onEditClick(s) {
      this.$emit("editSaver", s);
    },
    async onDeleteClick(s) {
      const result = await window.api.deleteSaverDialog(s);
      if ( result === 1 ) {
        this.$emit("deleteSaver", s);
      }
    }
  }
};
</script>

// src/renderer/components/SaverSummary.svelte
<div class="saver-description">
  {#if saver}
    {saver.name}
    <h1>
      {saver.name} 
      {#if saver.aboutUrl && saver.aboutUrl !== ""}<small><a href="{saver.aboutUrl}" on:click={open}>learn more</a></small>{/if}
    </h1>
    {#if saver.editable}
      <div class="actions">
        <button
          class="btn btn-outline-secondary btn-sm edit" 
          href="#"
          on:click="{onEditClick}"
        >
        edit
        </button>
        <button
          class="btn btn-outline-secondary btn-sm" 
          href="#"
          on:click="{onDeleteClick}"
        >
          delete
        </button>
      </div>
    {/if}

    <p>{saver.description}</p>
    {#if saver.author && saver.author !== ""}
      <span>
        by: {saver.author}
      </span>
    {/if}
  {/if}
</div>

<script>
	import { createEventDispatcher } from "svelte";

  const dispatch = createEventDispatcher();

  export let saver;

  function open(event) {
    event.preventDefault();
    window.api.openUrl(event.target.href);
  }

  async function onEditClick() {
    dispatch("editScreensaver", {
      saver
    });
  }

  async function onDeleteClick() {
    const result = await window.api.deleteSaverDialog(saver);
    if ( result === 1 ) {
      dispatch("deleteScreensaver", {
        saver
      });
    }
  }
</script>
