// src/renderer/components/SaverList.svelte
<div class="saver-list-wrapper">
  <h1>Screensavers</h1>
  <ul class="saver-list list-group-flush">
    {#each savers as saver (saver.key)}
      <li class="{saver.key == current ? CHECKED_CLASS : UNCHECKED_CLASS}">
        <div>
          <label>
            <div class="body">
              <input
                type="radio" 
                name="screensaver" 
                bind:group="{current}"
                data-name="{saver.name}" 
                value="{saver.key}" 
                checked="{saver.key == current}"
                onchange={onSelect}
                >

              <b>{saver.name}</b>
              <template v-if="saver.editable === true">
                &nbsp;(<small>custom</small>)
              </template>
      
              <div class="description">
                <small>{saver.description}</small>
              </div>
            </div>
          </label>
        </div>
      </li>
    {/each}
  </ul>
</div>

<script>
  let { savers, current = $bindable(), saverPicked } = $props();

  const UNCHECKED_CLASS = "list-group-item flex-column entry";
  const CHECKED_CLASS = `${UNCHECKED_CLASS} active`;

  function onSelect(e) {
    saverPicked({
      saver: e.target.value
    });
  }
</script>

// app/ui/saver-list.jsx
'use strict';
var React = require('react');

module.exports = React.createClass({
  getInitialState: function() {
    return {
      value: this.props.current
    };
  },
  onChanged: function (e) {
    this.setState({
      key: e.currentTarget.value
    });
  },
  handleChange: function(event) {
    this.setState({value: event.target.value});
  },
  render: function() {
    var self = this;
    var nodes = this.props.data.map(function(s, i) {
      var is_checked = (s.key === self.state.value);
      var authorClass = "external author";
      var aboutUrlClass = "external aboutUrl";
      var watcherClass = "watcher";
      
      if ( typeof(s.author) === "undefined" || s.author === "" ) {
        authorClass = authorClass + " hide";
      }
      if ( typeof(s.aboutUrl) === "undefined" || s.aboutUrl === "" ) {
        aboutUrlClass = aboutUrlClass + " hide";
      }

      console.log(s.editable);
      if ( s.editable === true ) {
        
      }
      else {
        watcherClass = watcherClass = " hide";
      }
      
      return (
        <li className={"list-group-item entry"} key={i}>
          <div className={"media-body"}>
            <label>
              <div className={"body"}>
                <input type="radio" name="screensaver" value={s.key} onChange={self.onChanged} defaultChecked={is_checked} />
                <b>{s.name}</b>
                <p className={"description"}>{s.description}</p>
                <span className={authorClass}>
                  {s.author} //
                </span>
                <a className={aboutUrlClass} href={s.aboutUrl}>learn more</a>
                <a className={watcherClass} href="#" data-key={s.key}>edit!</a>
              </div>
            </label>
          </div>
        </li>
      );
    });

    return(<ul className={"list-group"}>{nodes}</ul>);
  }
});
