// app/js/prefs.jsx
import "jquery";
import "bootstrap";

const React = require("react");
const ReactDOM = require("react-dom");
const AutoLaunch = require("auto-launch");
const path = require("path");

const _ = require("lodash");
const Noty = require("noty");

import OptionsForm from "./components/options-form.jsx";
import Preview from "./components/preview.jsx";
import SaverList from "./components/saver-list.jsx";

const shell = window.require("electron").shell;
const {BrowserWindow} = window.require("electron").remote;

(function() {
  var electron = window.require("electron");
  const {ipcRenderer} = window.require("electron");
  const {crashReporter} = window.require("electron");

  var savers = require("../lib/savers.js");
  var remote = window.require("electron").remote;
  var appName = remote.getGlobal("APP_NAME");
  var appVersion = remote.getGlobal("APP_VERSION");
  var defaultSaverRepo = remote.getGlobal("SAVER_REPO");
  var appRepo = remote.getGlobal("APP_REPO");
  var updateAvailable = remote.getGlobal("NEW_RELEASE_AVAILABLE");

  var ravenUrl = remote.getGlobal("RAVEN_URL");
  
  const {dialog} = require("electron").remote;

  var appLauncher = new AutoLaunch({
	  name: appName
  });
    
  var saverOpts = {};
  var url_opts = {};
  
  // parse incoming URL params -- we'll get a link to the current screen images for previews here
  var tmpParams = new URLSearchParams(document.location.search);

  // the main app will pass us a screenshot URL, here it is
  var screenshot = decodeURIComponent(tmpParams.get("screenshot"));

  if ( typeof(ravenUrl) !== "undefined" ) {
    Raven.config(ravenUrl).install();
  }
  
  crashReporter.start(remote.getGlobal("CRASH_REPORTER"));

  ipcRenderer.on("savers-updated", (event, arg) => {
    var val, s;

    console.log("handle savers-updated event");
    val = getCurrentScreensaver();

    renderList(false);
  });

  console.log("appLauncher " + appName);
  appLauncher.isEnabled().then(function(enabled){
    console.log("auto launch enabled?: " + enabled);
	  if (enabled) {
      document.querySelector("input[name=auto_start]").setAttribute("checked", "checked");
    }
  }).catch(function(err) {
    console.log("appLauncher error", err);
  });
  
  var el = document.querySelector("body > header div h1");
  if ( el ) {
    el.innerHTML = appName;
  }

  el = document.querySelector("body > header div .version");
  if ( el ) {
    el.innerHTML = appVersion;
  }
  
  // if the preview div didn't have a height, figure one out by getting
  // the width and making it proprtional to the main screen. at the moment,
  // the div will never have a height at this point unless someone specifically
  // hacks the CSS to make it work differently
  var getPreviewUrlOpts = function() {
    var tmp = {
      width: document.querySelector("#preview").offsetWidth,
      height: document.querySelector("#preview").offsetHeight,
      screenshot: screenshot,
      preview: 1
    };

    if ( tmp.height == 0 ) {
      var atomScreen = electron.screen;
      var size = atomScreen.getPrimaryDisplay().bounds;
      var ratio = size.height / size.width;
      tmp.height = tmp.width * ratio;
      //console.log("setting preview opts to", url_opts);
    }

    return tmp;
  };

  var loadPreview = function(s) {
    url_opts = getPreviewUrlOpts();

    ReactDOM.render(
      <Preview saver={s} url_opts={url_opts} saver_opts={saverOpts} />,
      document.getElementById("preview")
    );
  };

  var getCurrentScreensaver = function() {
    var el = document.querySelector("input[name=screensaver]:checked")
    if ( el !== null ) {
      return el.value;
    }

    return undefined;
  };

  /**
   * the user has updated the settings for this screensaver,
   * let's stash that data and redraw.
   */
  var optionsUpdated = function(data) {
    saverOpts = data;
    var current = getCurrentScreensaver();
    var s = savers.getByKey(current);
    redraw(s);        
  };
  
  var loadOptionsForm = function(s) {
    ReactDOM.render(
      <OptionsForm saver={s} onChange={(x) => optionsUpdated(x)} />,
      document.getElementById("options")
    );
  };
  
  var closeWindow = function() {
    var window = remote.getCurrentWindow();
    window.close();
  };

  var redraw = function(s) {
    var current_list_item = document.querySelector("#savers .list-group-item.active");
    if ( current_list_item !== null ) {
      current_list_item.classList.remove("active");
    }
    
    if ( typeof(s) === "undefined" ) {
      var current = getCurrentScreensaver();
      s = savers.getByKey(current);
    }

    if ( typeof(s) !== "undefined" ) {
      loadPreview(s);
      loadOptionsForm(s);

      var radio = document.querySelector("[name=screensaver]:checked");
      var el = radio.closest("li");
      var authorClass = "external author";
      var aboutUrlClass = "external aboutUrl";
      var buttonWrapClass = "hide";

      el.classList.add("active");
      
      if ( typeof(s.author) === "undefined" || s.author === "" ) {
        authorClass = authorClass + " hide";
      }
      if ( typeof(s.aboutUrl) === "undefined" || s.aboutUrl === "" ) {
        aboutUrlClass = aboutUrlClass + " hide";
      }

      if ( s.editable === true ) {
        buttonWrapClass = "buttons";
      }
      
      ReactDOM.render(
        <div>
          <h1 className={"name"}>{s.name} <a className={aboutUrlClass} href={s.aboutUrl}>learn more</a></h1>
          <p className={"description"}>{s.description}</p>
          <span className={authorClass}>
            {s.author}
          </span>
        </div>,
        document.getElementById("details")
      );

    }
  };

  var onResize = function() {
    redraw();
  };
  
  var handleLinkClick = function(event) {
    event.preventDefault();
    shell.openExternal(this.href);
  };
  
  var renderList = function(doScroll) {
    if ( typeof(doScroll) === "undefined" ) {
      doScroll = true;
    }

    savers.listAll(function(entries) {
      var current = savers.getCurrent();

      ReactDOM.render(
        <SaverList current={current} data={entries} />,
        document.getElementById("savers")
      );

      // scroll to the currently selected screensaver
      if ( doScroll === true ) {
        var $target = $("input[name=screensaver]:checked");
        if ( $target.length > 0 ) {
          var $list = $("#savers");
          $list.scrollTop($list.scrollTop() - $list.offset().top + $target.offset().top - 25);
        }
      }
      
      var s = savers.getByKey(current);
      redraw(s);

      var radios = document.querySelectorAll("input[name=screensaver]");
      for ( var i = 0; i < radios.length; i++ ) {
        radios[i].addEventListener("click", screensaverChanged, false);
      }

      var links = document.querySelectorAll("a.watcher");
      for ( var i = 0; i < links.length; i++ ) {
        links[i].addEventListener("click", openSaverInWatcher, false);
      }
      links = document.querySelectorAll("a.delete");
      for ( var i = 0; i < links.length; i++ ) {
        links[i].addEventListener("click", deleteSaver, false);
      }

      links = document.querySelectorAll("a[href^=\"http\"]");
      for ( var i = 0; i < links.length; i++ ) {
        links[i].addEventListener("click", handleLinkClick, false);
      }
    });
  };


  var handlePathChoice = function(result) {
    if ( result !== undefined ) {
      data = result;
      document.querySelector("[name=localSource]").value = data;
    }
  };

  var addNewSaver = function(e) {
    var prefsUrl = "file://" + __dirname + "/new.html";
    prefsUrl = prefsUrl + "?screenshot=" + encodeURIComponent(screenshot);

    var w = new BrowserWindow({
      width:450,
      height:500,
      resizable:true
    });

    w.loadURL(prefsUrl);
    e.preventDefault();
  };

  
  var showPathChooser = function(e) {
    e.preventDefault();
    dialog.showOpenDialog(
      {
        properties: [ "openDirectory", "createDirectory" ]
      },
      handlePathChoice );

  };

  /**
   * open the screensaver in preview window
   */
  var openSaverInWatcher = function(e) {
    var src = e.target.dataset.src;
    ipcRenderer.send("open-editor", {
      src: src,
      screenshot: screenshot
    });

    e.preventDefault();
  };

  var deleteSaver = function(e) {
    var key = e.target.dataset.key;
    var s = savers.getByKey(key);
    
    dialog.showMessageBox(
      {
        type: "info",
        title: "Are you sure?",
        message: "Are you sure you want to delete this screensaver?",
        detail: "Deleting screensaver " + s.name,
        buttons: ["No", "Yes"],
        defaultId: 0
      },
      function(result) {
        if ( result === 1 ) {
          savers.delete(key, function() {
            ipcRenderer.send("savers-updated", key);
          });
        }
      }
    );

    e.preventDefault();
  };
  
  var updatePrefs = function() {
    var delay = document.querySelector("select[name=delay]").value;
    var sleep = document.querySelector("select[name=sleep]").value;    
    var do_lock = document.querySelector("input[name=lock_screen]").checked;
    var disable_on_battery = document.querySelector("input[name=disable_on_battery]").checked;
    var val = getCurrentScreensaver();
    
    var repo = document.querySelector("input[name=repo]").value;
    var localSource = document.querySelector("[name=localSource]").value;

    if ( val !== undefined ) {
      savers.setCurrent(val, saverOpts);
    }

    delay = parseInt(delay, 10);   
    savers.setDelay(delay);

    sleep = parseInt(sleep, 10);
    savers.setSleep(sleep);
    
    savers.setLock(do_lock);
    savers.setDisableOnBattery(disable_on_battery);
    
    savers.setSource(repo);
    savers.setLocalSource(localSource);

    savers.write(function() {
      if ( document.querySelector("input[name=auto_start]").checked === true ) {
        console.log("set auto_start == true");
	      appLauncher.enable().then(function(x) { }).then(function(err){
          console.log("ERR", err);
        });
      }
      else {
        console.log("set auto start == false");
	      appLauncher.disable().then(function(x) { });
      }

      /* new Noty({
         type: 'success',
         layout: 'topRight',
         timeout: 1000,
         text: 'Changes saved!',
         animation: {
         open: null
         }
         }).show();      
       */
      closeWindow();
    });
  }; // updatePrefs

  var screensaverChanged = function() {
    var val = getCurrentScreensaver();
    var s = savers.getByKey(val);
    
    saverOpts = {};
    redraw(s);
  };

  document.querySelector(".create").addEventListener("click", addNewSaver, false);
  document.querySelector(".cancel").addEventListener("click", closeWindow, false);
  document.querySelector(".pick").addEventListener("click", showPathChooser, false);
  document.querySelector(".save").addEventListener("click", updatePrefs, false);

  window.addEventListener("resize", onResize, true);

  //
  // i'm seeing a weird issue where both tabs can be marked as active,
  // which ruins the output. this little snippet seems to handle that
  // issue.
  // @see https://github.com/twbs/bootstrap/issues/19374
  $(document).ready(function() {
    $(".nav-tabs .nav-link")
       .click(function() {
        $(".tab-pane.active,.nav-link.active").removeClass("active");
      });
  });
  
  var basePath = window.require("electron").remote.getGlobal("basePath");
  savers.init(basePath, function() {
    el = document.querySelector("[name=repo]");
    el.value = savers.getSource().repo;
    el.setAttribute("placeholder", defaultSaverRepo);

    document.querySelector("[name=localSource]").value = savers.getLocalSource();
    el = document.querySelector("select[name='delay'] option[value='" + savers.getDelay() + "']");
    if ( el !== null ) {
      el.setAttribute("selected", "selected");
    }

    el = document.querySelector("select[name='sleep'] option[value='" + savers.getSleep() + "']");
    if ( el !== null ) {
      el.setAttribute("selected", "selected");
    }
    
    if ( savers.getLock() === true ) {
      document.querySelector("input[name=lock_screen][type=checkbox]").setAttribute("checked", "checked");
    }

    if ( savers.getDisableOnBattery() === true ) {
      document.querySelector("input[name=disable_on_battery]").setAttribute("checked", "checked");
    }
    renderList();
  });
  
  if ( updateAvailable === true ) {
    dialog.showMessageBox(
      {
        type: "info",
        title: "Update Available!",
        message: "There's a new update available! Would you like to download it?",
        buttons: ["No", "Yes"],
        defaultId: 0
      },
      function(result) {
        console.log(result);
        if ( result === 1 ) {
          shell.openExternal("https://github.com/" + appRepo + "/releases/latest");
        }
      }
    );
  }

})();

// src/renderer/Prefs.vue
<template>
  <div id="prefs">
    <div class="content">
      <b-tabs>
        <b-tab title="Screensavers" active>
          <div class="container-fluid">
            <div class="row">
              <!-- left pane -->
              <div class="col-sm-6 col-md-6">
                <saver-list
                  v-if="isLoaded"
                  v-bind:savers="savers"
                  v-bind:current="saver"
                  v-on:editSaver="editSaver"
                  v-on:deleteSaver="deleteSaver"
                  @change="onSaverPicked"></saver-list>
              </div>
              
              <!-- right pane -->
              <div class="col-sm-6 col-md-6 saver-detail">
                <template v-if="isLoaded">
                  <saver-summary :saver="saverObj"></saver-summary>
                  <saver-preview
                    :bus="bus"
                    :saver="savers[saverIndex]"
                    :screenshot="screenshot"
                    :options="options[saver]"
                    v-if="savers[saverIndex] !== undefined"></saver-preview>
                  <saver-options
                    :saver="saver"
                    :options="saverOptions"
                    :values="options[saver]"
                    @change="onOptionsChange"
                    v-on:saverOption="updateSaverOption"></saver-options>
                </template>
              </div>
            </div>
          </div>
        </b-tab>
        <b-tab title="Preferences">
          <div class="container-fluid">
            <prefs-form
              :prefs="prefs"
              v-on:localSourceChange="localSourceChange"></prefs-form>
          </div>
          <div class="container-fluid">
            <button class="btn btn-large btn-positive reset-to-defaults"
                    v-on:click="resetToDefaults">Reset to Defaults</button>
          </div>
        </b-tab>
      </b-tabs>
    </div> <!-- content -->
    <footer class="footer d-flex justify-content-between">
      <div>
        <button class="btn btn-large btn-positive create" v-on:click="createNewScreensaver">Create Screensaver</button>
      </div>
      <div>
        <button class="btn btn-large btn-default cancel" v-on:click="closeWindow">Cancel</button>
        <button class="btn btn-large btn-positive save"  v-on:click="saveData" :disabled="disabled">Save</button>
      </div>
    </footer>
  </div> <!-- #prefs -->
</template>

<script>
import Vue from 'vue';
import SaverList from '@/components/SaverList';
import SaverPreview from '@/components/SaverPreview';
import SaverOptions from '@/components/SaverOptions';
import SaverSummary from '@/components/SaverSummary';
import PrefsForm from '@/components/PrefsForm';
import Noty from "noty";
  
const {dialog} = require("electron").remote;
  
export default {
  name: 'prefs',
  components: {
    SaverList, SaverOptions, SaverPreview, SaverSummary, PrefsForm
  },
  mounted() {
    this.ipcRenderer.on("savers-updated", (event, arg) => {
      this.getData();
    });
    this.ipcRenderer.on("request-open-add-screensaver", (event, arg) => {
      this.createNewScreensaver();
    });

    if ( this.manager === undefined ) {
      return;
    }

    this.getData();
    this.getCurrentSaver();

    if ( this.$electron.remote.getGlobal("NEW_RELEASE_AVAILABLE") ) {
      this.$nextTick(() => {
        this.renderUpdateNotice();
      });
    }
    
  },
  data() {
    return {
      savers: [],
      prefs: {},
      options: {},
      saver: undefined,
      disabled: false
    }
  },
  computed: {
    bus: function() {
      return new Vue();
    },
    currentWindow: function() {
      return this.$electron.remote.getCurrentWindow();
    },
    manager: function() {
      return this.currentWindow.savers;
    },
    ipcRenderer: function() {
      return this.$electron.ipcRenderer;
    },
    isLoaded: function() {
      return ( this.saver !== undefined &&
               typeof(this.savers) !== "undefined" &&
               this.savers.length > 0);
    },
    saverIndex: function() {
      return this.savers.findIndex((s) => s.key === this.saver);
    },
    saverOptions: function() {
      var self = this;
      if ( ! this.isLoaded ) {
        return undefined;
      }

      return this.savers[this.saverIndex].options;
    },
    saverValues: function() {
      if ( typeof(this.prefs) === "undefined" ) {
        return {};
      }
      return this.options[this.saver];
    },
    saverSettings: function() {
      return this.savers[this.saverIndex].settings;
    },
    saverObj: function() {
      return this.savers[this.saverIndex];
    },
    params: function() {
      // parse incoming URL params -- we'll get a link to the current screen images for previews here
      return new URLSearchParams(document.location.search);
    },
    screenshot: function() {
      // the main app will pass us a screenshot URL, here it is
      return decodeURIComponent(this.params.get("screenshot"));
    }
  },
  methods: {
    onOptionsChange(e) {
      this.bus.$emit('options-changed', this.options[this.saver]);
    },
    onSaverPicked(e) {
      this.saver = e.target.value;
      this.bus.$emit('saver-changed', this.saverObj);
    },
    resetToDefaults(e) {
      dialog.showMessageBox(
        {
          type: "info",
          title: "Are you sure?",
          message: "Are you sure you want to reset to the default settings?",
          buttons: ["No", "Yes"],
          defaultId: 0
        },
        (result) => {
          if ( result === 1 ) {
            var tmp = this.manager.getDefaults();
            this.prefs = Object.assign(this.prefs, tmp);

            this.saveData(false).then(() => {
              this.manager.reload(() => {
                this.getData();

                new Noty({
                  type: "success",
                  layout: "topRight",
                  timeout: 1000,
                  text: "Settings reset!",
                  animation: {
                    open: null
                  }
                }).show();
              }); // reload
            }); // saveData
          }
        }
      );
    },  
    getData() {
      this.manager.listAll((entries) => {

        this.savers = entries;
        var tmp = this.manager.getConfigSync();
        if ( tmp.options === undefined ) {
          tmp.options = {};
        }
        
        // ensure default settings in the config for all savers
        for(var i = 0; i < this.savers.length; i++ ) {
          var s = this.savers[i];

          if ( tmp.options[s.key] === undefined ) {
            tmp.options[s.key] = {};
          }

          tmp.options[s.key] = s.settings;
        }

        this.options = Object.assign({}, this.options, tmp.options);
        // https://vuejs.org/v2/guide/reactivity.html
        // However, new properties added to the object will not
        // trigger changes. In such cases, create a fresh object
        // with properties from both the original object and the mixin object:
        this.prefs = Object.assign({}, this.prefs, tmp);
        this.bus.$emit('saver-changed', this.saverObj);
      });
    },
    getCurrentSaver() {
      this.saver = this.manager.getCurrent();
    },
    createNewScreensaver() {
      this.saveData(false);
      this.ipcRenderer.send("open-add-screensaver", this.screenshot);
    },
    editSaver(s) {
      var opts = {
        src: s.src,
        screenshot: this.screenshot
      };
      this.ipcRenderer.send("open-editor", opts);
    },
    deleteSaver(s) {
      var index = this.savers.indexOf(s);
      this.savers.splice(index, 1);

      this.manager.delete(s, () => {
        this.ipcRenderer.send("savers-updated", s.key);
      });

    },
    updateSaverOption(saver, name, value) {
      var tmp = this.options;
      var update = {};
      
      //update[saver] = {};
      update[saver] = Object.assign({}, tmp[saver]);    
      update[saver][name] = value;
    

      //this.prefs.options = Object.assign({}, tmp, update);
      this.options = Object.assign({}, this.options, update);
    },
    closeWindow() {
      this.currentWindow.close();
    },
    saveData(doClose) {
      if ( typeof(doClose) === "undefined" ) {
        doClose = true;
      }
      
      this.disabled = true;

      // @todo should this use Object.assign?
      this.prefs.saver = this.saver;
      this.prefs.options = this.options;
      
      this.manager.updatePrefs(this.prefs, () => {
        this.disabled = false;
        this.ipcRenderer.send("prefs-updated", this.prefs);
        this.ipcRenderer.send("set-autostart", this.prefs.auto_start);
        if ( doClose ) {
          this.closeWindow();
        }
        else {
          return Promise.resolve();
        }
      });
    },
    renderUpdateNotice() {
      dialog.showMessageBox(
        {
          type: "info",
          title: "Update Available!",
          message: "There's a new update available! Would you like to download it?",
          buttons: ["No", "Yes"],
          defaultId: 0
        },
        (result) => {
          if ( result === 1 ) {
            var appRepo = this.$electron.remote.getGlobal("APP_REPO");
            this.$electron.shell.openExternal("https://github.com/" + appRepo + "/releases/latest");
          }
        }
      );
    },
    localSourceChange(ls) {
      var tmp = {
        localSource: ls
      };
      this.prefs = Object.assign(this.prefs, tmp);
    }
  }
}; 
</script>
